spring:
  sql:
    init:
      platform: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_app_dev
    username: recipe_dev_user
    password: Dwanford123
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
