version: 2.1
executors:
  main-executor:
    docker:
      - image: cimg/openjdk:18.0
        auth:
          # ensure you have first added these secrets
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  build:

    executor: main-executor
    steps:
      - checkout
      - run: |
          mvn integration-test

workflows:
  tests-workflow:
    jobs:
      - build